# Generated by Django 6.0 on 2026-07-12 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='R.U.T.')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('giro', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre Sucursal')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Nº Factura')),
                ('tipo_documento', models.CharField(default='FACTURA ELECTRONICA', max_length=50)),
                ('fecha_emision', models.DateField()),
                ('neto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('archivo_origen', models.CharField(blank=True, max_length=255, null=True, verbose_name='Archivo de origen')),
                ('estado_despacho', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DESPACHADO', 'Despachado')], default='PENDIENTE', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='inventario.cliente')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('numero', 'tipo_documento')},
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='despacho', to='inventario.factura')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Nº Guía Abastecimiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Principal')),
                ('codigo_alternativo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Alternativo')),
                ('cant_alternativo', models.IntegerField(default=1, verbose_name='Cantidad Alternativo 1 (Unidad)')),
                ('codigo_alternativo_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Alternativo 2')),
                ('cant_alternativo_2', models.IntegerField(default=1, verbose_name='Cantidad Alternativo 2 (Caja)')),
                ('codigo_alternativo_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Alternativo 3')),
                ('cant_alternativo_3', models.IntegerField(default=1, verbose_name='Cantidad Alternativo 3')),
                ('descripcion', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(blank=True, default='UN', max_length=10, null=True)),
                ('stock_actual', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock Actual')),
                ('stock_real', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock Real (Contado)')),
                ('stock_minimo', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock Mínimo')),
                ('stock_sistema', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock Sistema ERP')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Precio de Venta')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='inventario__codigo_d18360_idx'), models.Index(fields=['activo'], name='inventario__activo_041dee_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('stock_actual_anterior', models.IntegerField(blank=True, null=True)),
                ('stock_actual_nuevo', models.IntegerField(blank=True, null=True)),
                ('stock_real_anterior', models.IntegerField(blank=True, null=True)),
                ('stock_real_nuevo', models.IntegerField(blank=True, null=True)),
                ('detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_stock', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Historial de Stock',
                'verbose_name_plural': 'Historiales de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleGuiaAbastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.guiaabastecimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.IntegerField()),
                ('total_linea', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Bodega')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodegas', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['sucursal__nombre', 'nombre'],
                'unique_together': {('sucursal', 'codigo')},
            },
        ),
    ]
