# Generated by Django 6.0 on 2026-09-24 14:02

from django.db import migrations, models


def normalizar_textos(apps, schema_editor):
    campos = {
        'Cliente': ['giro', 'telefono'],
        'Factura': ['archivo_origen'],
        'HistorialStock': ['detalle'],
        'Producto': ['codigo_alternativo', 'codigo_alternativo_2', 'codigo_alternativo_3', 'unidad_medida'],
        'Sucursal': ['direccion'],
    }
    for nombre, nombres_campos in campos.items():
        modelo = apps.get_model('inventario', nombre)
        for campo in nombres_campos:
            modelo.objects.using(schema_editor.connection.alias).filter(**{campo + '__isnull': True}).update(**{campo: ''})


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalizar_textos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cliente',
            name='giro',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='factura',
            name='archivo_origen',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Archivo de origen'),
        ),
        migrations.AlterField(
            model_name='historialstock',
            name='detalle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_alternativo',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código Alternativo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_alternativo_2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código Alternativo 2'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_alternativo_3',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Código Alternativo 3'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, default='UN', max_length=10),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
